# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f7dd8338ece6c96c9ae798e7dfe710092ae09b9c923a9bd687d89284045a47b73f8beb57c035a2249eec457836a43cdbdcee89e9ef3708c687124702097a075
  # sendgrid_user_name: RajinBelajar
  # sendgrid_password: RajinBelajar*
  sendgrid_user_name: mhad_zakaria
  sendgrid_password: sgmhad19#9
  firebase_url: "https://chatrajin.firebaseio.com/"
  firebase_apiKey: AIzaSyCipYYpV1VpQv9vRAE8CgvYU5kxfBxS-d4
  firebase_authDomain: chatrajin.firebaseapp.com
  firebase_databaseURL: https://chatrajin.firebaseio.com
  firebase_projectId: chatrajin
  firebase_storageBucket: chatrajin.appspot.com
  firebase_messagingSenderId: 702764009377\
  ipay_merchant_key: xxxxxxxxx
  ipay_merchant_code: xxxxxxx
  ipay_merchant_company: XXXX Sdn Bhd
  facebook_api_key: 946724172145626
  facebook_secret: f3e1cd91f3b24fa1c4bf688f59be4d95

test:
  secret_key_base: 5b8a203a8126367d97e9768f4dd650cc37b4c836b92c99ab32bb47ee412acd1dc20d4931749f8cfdce59b94c51b18a29773d3f3d8ae179e94f91241dfeb04e9d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
